Repository Kernel360/KBE5-Thisway-BE, pull requests merged in 2025-06, with the labels that each got.

#78 업체 응답 dto에 업체 ID 정보 추가
  src/main/java/org/thisway/company/dto/response/CompanyResponse.java
Labels: enhancement

#83 Page 정보 공통 클래스 생성
  src/main/java/org/thisway/common/PageInfo.java
Labels: enhancement

#85 시동 상태 변경에 따른 시동 상태 업데이트 로직 구현
  src/main/java/org/thisway/vehicle/controller/VehicleController.java
  src/main/java/org/thisway/vehicle/entity/Vehicle.java
  src/main/java/org/thisway/vehicle/service/VehicleService.java
Labels: enhancement

#90 CORS 정책 추가
  src/main/java/org/thisway/config/WebConfig.java
  src/main/java/org/thisway/security/config/SecurityConfig.java
Labels: enhancement

#91 사용자 수 요약 API 생성
  src/main/java/org/thisway/member/controller/MemberController.java
  src/main/java/org/thisway/member/dto/MemberSummaryDto.java
  src/main/java/org/thisway/member/dto/response/MemberSummaryResponse.java
  src/main/java/org/thisway/member/entity/MemberRole.java
  src/main/java/org/thisway/member/repository/MemberRepository.java
  src/main/java/org/thisway/member/service/MemberService.java
  src/main/java/org/thisway/security/dto/request/MemberDetails.java
  src/main/java/org/thisway/security/filter/JwtAuthenticationFilter.java
  src/main/java/org/thisway/security/handler/JsonAuthenticationSuccessHandler.java
  src/main/java/org/thisway/security/service/CustomUserDetailsService.java
  src/main/java/org/thisway/security/service/SecurityService.java
  src/test/java/org/thisway/member/controller/MemberControllerTest.java
  src/test/java/org/thisway/member/service/MemberServiceTest.java
  src/test/java/org/thisway/security/filter/JwtAuthenticationFilterTest.java
  src/test/java/org/thisway/security/service/SecurityServiceTest.java
Labels: enhancement

#95 Vehicle 인가 적용 및 VehicleRequestDto 불필요 필드명 제거
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/vehicle/controller/VehicleController.java
  src/main/java/org/thisway/vehicle/dto/request/VehicleCreateRequest.java
  src/main/java/org/thisway/vehicle/entity/Vehicle.java
  src/main/java/org/thisway/vehicle/repository/VehicleRepository.java
  src/main/java/org/thisway/vehicle/service/VehicleService.java
  src/test/java/org/thisway/vehicle/CarNumberValidationTest.java
  src/test/java/org/thisway/vehicle/controller/VehicleControllerTest.java
  src/test/java/org/thisway/vehicle/service/VehicleServiceTest.java
Labels: enhancement

#96 업체 관련 테스트코드 작성
  src/test/java/org/thisway/company/controller/CompanyControllerTest.java
  src/test/java/org/thisway/company/service/CompanyServiceTest.java
Labels: enhancement

#101 DATE_TIME_FORMATTER & _SEC 날짜 형식 변경
  src/main/java/org/thisway/log/converter/LogDataConverter.java
  src/main/java/org/thisway/log/service/LogService.java
  src/test/java/org/thisway/log/converter/LogDataConverterTest.java
Labels: bug

#103 GpsStatus enum 적용
  src/main/java/org/thisway/log/converter/LogDataConverter.java
  src/main/java/org/thisway/log/domain/GeofenceLogData.java
  src/main/java/org/thisway/log/domain/GpsLogData.java
  src/main/java/org/thisway/log/domain/GpsStatus.java
  src/main/java/org/thisway/log/domain/PowerLogData.java
  src/main/java/org/thisway/log/repository/LogRepository.java
  src/test/java/org/thisway/log/converter/LogDataConverterTest.java
  src/test/java/org/thisway/log/repository/LogRepositoryTest.java
Labels: enhancement

#107 Member 관련 COMPANY CHEF API 추가
  src/main/java/org/thisway/member/controller/CompanyChefMemberController.java
  src/main/java/org/thisway/member/dto/CompanyChefMemberDetailOutput.java
  src/main/java/org/thisway/member/dto/CompanyChefMemberRegisterInput.java
  src/main/java/org/thisway/member/dto/CompanyChefMemberSummaryOutput.java
  src/main/java/org/thisway/member/dto/CompanyChefMemberUpdateInput.java
  src/main/java/org/thisway/member/dto/CompanyChefMembersOutput.java
  src/main/java/org/thisway/member/dto/request/CompanyChefMemberRegisterRequest.java
  src/main/java/org/thisway/member/dto/request/CompanyChefMemberUpdateRequest.java
  src/main/java/org/thisway/member/dto/response/CompanyChefMemberDetailResponse.java
  src/main/java/org/thisway/member/dto/response/CompanyChefMemberSummaryResponse.java
  src/main/java/org/thisway/member/dto/response/CompanyChefMembersResponse.java
  src/main/java/org/thisway/member/repository/MemberRepository.java
  src/main/java/org/thisway/member/service/CompanyChefMemberService.java
  src/main/java/org/thisway/security/config/SecurityConfig.java
  src/main/java/org/thisway/security/config/policy/RequestAuthorizationPolicy.java
  src/main/java/org/thisway/security/config/policy/member/MemberAuthorizationPolicy.java
  src/test/java/org/thisway/member/controller/CompanyChefMemberControllerTest.java
  src/test/java/org/thisway/member/service/CompanyChefMemberServiceTest.java
  src/test/java/org/thisway/security/CompanyChefApiSecurityTest.java
Labels: enhancement

#116 ADMIN 멤버 요약 기능 잘못된 role code 수정
  src/main/java/org/thisway/member/service/CompanyChefMemberService.java
Labels: bug

#112 예외 처리 로그 정리
  src/main/java/org/thisway/common/CustomException.java
  src/main/java/org/thisway/common/GlobalExceptionHandler.java
Labels: refactor

#110 ADMIN API 정책 설정 추가
  src/main/java/org/thisway/security/config/policy/member/MemberAuthorizationPolicy.java
  src/test/java/org/thisway/member/controller/AdminMemberControllerTest.java
  src/test/java/org/thisway/security/AdminApiSecurityTest.java
Labels: enhancement

#118 Github Action 기반 CI/CD 구축
  .github/workflows/cd.yml
  .github/workflows/ci.yml
  build.gradle
Labels: enhancement

#120 Refactor/106 : VehicleResponse 응닶 값 변경 및 VehicleRequest mileage 기본값 0으로 설정
  src/main/java/org/thisway/vehicle/dto/request/VehicleCreateRequest.java
  src/main/java/org/thisway/vehicle/dto/response/VehicleResponse.java
  src/main/java/org/thisway/vehicle/entity/Vehicle.java
  src/main/java/org/thisway/vehicle/service/VehicleService.java
  src/test/java/org/thisway/vehicle/controller/VehicleControllerTest.java
  src/test/java/org/thisway/vehicle/service/VehicleServiceTest.java
Labels: refactor

#131 인가 정책에 Log 비인증 접근 추가
  src/main/java/org/thisway/log/service/LogService.java
  src/main/java/org/thisway/security/config/policy/auth/AuthAuthorizationPolicy.java
Labels: enhancement

#129 애뮬레이터 API 개발
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/emulator/controller/EmulatorController.java
  src/main/java/org/thisway/emulator/controller/dto/request/EmulatorRegisterRequest.java
  src/main/java/org/thisway/emulator/controller/dto/request/EmulatorUpdateRequest.java
  src/main/java/org/thisway/emulator/controller/dto/response/EmulatorDetailResponse.java
  src/main/java/org/thisway/emulator/controller/dto/response/EmulatorsResponse.java
  src/main/java/org/thisway/emulator/entity/Emulator.java
  src/main/java/org/thisway/emulator/service/EmulatorService.java
  src/main/java/org/thisway/emulator/service/dto/input/EmulatorCreateInput.java
  src/main/java/org/thisway/emulator/service/dto/input/EmulatorUpdateInput.java
  src/main/java/org/thisway/emulator/service/dto/output/EmulatorOutput.java
  src/main/java/org/thisway/emulator/service/dto/output/EmulatorsOutput.java
  src/main/java/org/thisway/security/config/policy/RequestAuthorizationPolicy.java
  src/main/java/org/thisway/security/config/policy/emulator/EmulatorAuthorizationPolicy.java
Labels: enhancement

#124 Feat/122 : VehicleModel(이전VehicleDetail) 등록 기능
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/vehicle/controller/VehicleModelController.java
  src/main/java/org/thisway/vehicle/dto/request/VehicleCreateRequest.java
  src/main/java/org/thisway/vehicle/dto/request/VehicleModelCreateRequest.java
  src/main/java/org/thisway/vehicle/dto/response/VehicleModelResponse.java
  src/main/java/org/thisway/vehicle/dto/response/VehicleModelsResponse.java
  src/main/java/org/thisway/vehicle/dto/response/VehicleResponse.java
  src/main/java/org/thisway/vehicle/entity/Vehicle.java
  src/main/java/org/thisway/vehicle/entity/VehicleModel.java
  src/main/java/org/thisway/vehicle/repository/VehicleDetailRepository.java
  src/main/java/org/thisway/vehicle/repository/VehicleModelRepository.java
  src/main/java/org/thisway/vehicle/service/VehicleModelService.java
  src/main/java/org/thisway/vehicle/service/VehicleService.java
  src/test/java/org/thisway/vehicle/controller/VehicleModelControllerTest.java
  src/test/java/org/thisway/vehicle/service/VehicleModelServiceTest.java
  src/test/java/org/thisway/vehicle/service/VehicleServiceTest.java
Labels: enhancement

#132 feat: 125 VehicleModel 전체 조회
  src/main/java/org/thisway/vehicle/controller/VehicleModelController.java
  src/main/java/org/thisway/vehicle/dto/response/VehicleModelsResponse.java
  src/main/java/org/thisway/vehicle/repository/VehicleModelRepository.java
  src/main/java/org/thisway/vehicle/service/VehicleModelService.java
Labels: enhancement

#136 차량 시동 상태 업데이트 로직 수정
  src/main/java/org/thisway/log/service/LogService.java
  src/main/java/org/thisway/vehicle/controller/VehicleController.java
  src/main/java/org/thisway/vehicle/service/VehicleService.java
  src/test/java/org/thisway/log/service/LogServiceTest.java
Labels: enhancement

#138 차량 누적 주행거리 업데이트 로직 추가
  src/main/java/org/thisway/log/service/LogService.java
  src/main/java/org/thisway/vehicle/entity/Vehicle.java
Labels: enhancement

#150 Gps 주기정보 날짜 포맷 저장 로직 추가
  src/main/java/org/thisway/log/service/LogService.java
Labels: enhancement

#148 Refactor/145: 차량 번호 등록 시 예외처리 핸들링
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/common/GlobalExceptionHandler.java
  src/main/java/org/thisway/vehicle/dto/request/VehicleModelCreateRequest.java
  src/main/java/org/thisway/vehicle/validation/ValidCarNumber.java
  src/test/java/org/thisway/vehicle/CarNumberValidationTest.java
Labels: refactor

#153 refactor: #152 Vehicle 수정(Update)시 VehicleModelId 값 요청에 포함
  src/main/java/org/thisway/vehicle/dto/request/VehicleUpdateRequest.java
  src/main/java/org/thisway/vehicle/entity/Vehicle.java
  src/main/java/org/thisway/vehicle/service/VehicleService.java
  src/main/java/org/thisway/vehicle/validation/VehicleUpdateValidator.java
  src/test/java/org/thisway/vehicle/controller/VehicleControllerTest.java
  src/test/java/org/thisway/vehicle/service/VehicleServiceTest.java
Labels: refactor

#165 운행 일지 테이블 분리 및 시동 위치 통계 조회 API 개발
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/log/repository/LogRepository.java
  src/main/java/org/thisway/log/service/LogService.java
  src/main/java/org/thisway/security/config/policy/RequestAuthorizationPolicy.java
  src/main/java/org/thisway/security/config/policy/statistics/StatisticsAuthorizationPolicy.java
  src/main/java/org/thisway/triplog/controller/StatisticController.java
  src/main/java/org/thisway/triplog/converter/ReverseGeocodingConverter.java
  src/main/java/org/thisway/triplog/dto/KakaoCoordToAddress.java
  src/main/java/org/thisway/triplog/dto/ReverseGeocodeResult.java
  src/main/java/org/thisway/triplog/dto/response/TripLocationStats.java
  src/main/java/org/thisway/triplog/entity/TripLog.java
  src/main/java/org/thisway/triplog/repository/TripLogRepository.java
  src/main/java/org/thisway/triplog/service/StatisticService.java
  src/main/java/org/thisway/triplog/service/TripLogService.java
  src/test/java/org/thisway/log/service/LogServiceTest.java
  src/test/resources/application.yml
Labels: enhancement

#177 시동 로그 수집 요청에 mid 추가
  src/main/java/org/thisway/log/dto/request/powerLog/PowerLogRequest.java
  src/test/java/org/thisway/log/service/LogServiceTest.java
Labels: enhancement

#172 Feat/155 : 통계 API 생성 및 조회
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/log/repository/LogRepository.java
  src/main/java/org/thisway/statistics/constant/StatisticConstants.java
  src/main/java/org/thisway/statistics/controller/StatisticController.java
  src/main/java/org/thisway/statistics/dto/response/StatisticResponse.java
  src/main/java/org/thisway/statistics/entity/Statistics.java
  src/main/java/org/thisway/statistics/repository/StatisticsRepository.java
  src/main/java/org/thisway/statistics/service/StatisticCalculationService.java
  src/main/java/org/thisway/statistics/service/StatisticPersistenceService.java
  src/main/java/org/thisway/statistics/service/StatisticQueryService.java
  src/main/java/org/thisway/statistics/service/StatisticService.java
  src/main/java/org/thisway/triplog/controller/StatisticController.java
  src/main/java/org/thisway/triplog/repository/TripLogRepository.java
  src/main/java/org/thisway/triplog/service/StatisticService.java
Labels: enhancement, refactor

#171 모니터링 시스템 개발 및 배포 환경 구성
  build.gradle
  infra/dev/db/init-schema.sql
  infra/dev/docker-compose.yml
  infra/dev/monitoring/Dockerfile
  infra/dev/monitoring/prometheus.dev.yml
  infra/prod/monitoring/grafana/Dockerfile
  infra/prod/monitoring/grafana/provisioning/datasources/datasource.yml
  infra/prod/monitoring/prometheus/Dockerfile
  infra/prod/monitoring/prometheus/prometheus.prod.yml
  src/main/java/org/thisway/security/config/policy/ActuatorAuthorizationPolicy.java
  src/main/java/org/thisway/security/config/policy/auth/AuthAuthorizationPolicy.java
  src/main/java/org/thisway/security/controller/HealthContoller.java
Labels: enhancement

#182 애뮬레이터에서 GPS Log 전송시 같은 oTime이 여러개 있을 때, GPS Tracking 에서 에러 해결
  src/main/java/org/thisway/log/repository/LogRepository.java
Labels: bug

#185 요청, 응답 로깅 시점 분리 및 로깅 내용 정리
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/common/GlobalExceptionHandler.java
  src/main/java/org/thisway/logging/advice/RequestBodyLoggingAdvice.java
  src/main/java/org/thisway/logging/advice/ResponseBodyLoggingAdvice.java
  src/main/java/org/thisway/logging/filter/LoggingFilter.java
Labels: refactor

#194 fix: #190 리스트 슬라이스 버그 수정
  src/main/java/org/thisway/triplog/service/TripLogServiceImpl.java
Labels: bug

#192 Refactor/191 : 가동률이 0%인 시간대를 최저 시간대 계산에서 제외
  src/main/java/org/thisway/statistics/dto/response/StatisticResponse.java
  src/main/java/org/thisway/statistics/service/StatisticCalculationService.java
  src/main/java/org/thisway/statistics/service/StatisticQueryService.java
Labels: refactor

#196 GPS 로그 시간 처리 개선 및 분 단위 필드 추가
  src/main/java/org/thisway/log/dto/request/gpsLog/GpsLogEntry.java
  src/main/java/org/thisway/log/service/GpsLogSaveService.java
  src/test/java/org/thisway/log/service/GpsLogSaveServiceTest.java
Labels: enhancement, refactor

#193 빌드 관련 정리
  build.gradle
  infra/dev/docker-compose.yml
  infra/dev/env/common.env
  infra/dev/env/mysql.env
  infra/dev/env/rabbitmq.env
  infra/dev/env/redis.env
  infra/dev/monitoring/Dockerfile
  infra/dev/monitoring/prometheus.dev.yml
  infra/dev/mysql/conf/my.conf
  infra/dev/mysql/db/00-init-schema.sql
  infra/dev/mysql/db/init-db.sql
  infra/stress/stress_avg.js
  infra/stress/stress_test.js
  src/main/java/org/thisway/company/controller/AdminCompanyController.java
  src/main/java/org/thisway/config/ampq/RabbitMQConfig.java
  src/main/java/org/thisway/log/consumer/GpsLogConsumer.java
  src/main/java/org/thisway/log/dto/request/powerLog/PowerLogRequest.java
  src/main/java/org/thisway/logging/advice/RequestBodyLoggingAdvice.java
  src/main/java/org/thisway/logging/advice/ResponseBodyLoggingAdvice.java
  src/main/java/org/thisway/logging/constant/LoggingExcludeUrls.java
  src/main/java/org/thisway/logging/filter/LoggingFilter.java
Labels: enhancement, refactor
