Repository Kernel360/KBE5-Thisway-BE, pull requests merged in 2025-05, with the labels that each got.

#3 로컬 및 개발 환경별 Gradle 설정 파일 분리 및 적용
  .gitignore
  build.gradle
Labels: enhancement

#14 Member 등록 API 개발
  src/main/java/org/thisway/member/controller/MemberController.java
  src/main/java/org/thisway/member/dto/request/MemberRegisterRequest.java
  src/main/java/org/thisway/member/entity/Member.java
  src/main/java/org/thisway/member/repository/MemberRepository.java
  src/main/java/org/thisway/member/service/MemberService.java
  src/test/java/org/thisway/member/controller/MemberControllerTest.java
  src/test/java/org/thisway/member/service/MemberServiceTest.java
  src/test/java/org/thisway/member/support/MemberFixture.java
Labels: enhancement

#17 Member 삭제 API 개발
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/member/controller/MemberController.java
  src/main/java/org/thisway/member/repository/MemberRepository.java
  src/main/java/org/thisway/member/service/MemberService.java
  src/test/java/org/thisway/member/controller/MemberControllerTest.java
  src/test/java/org/thisway/member/service/MemberServiceTest.java
  src/test/java/org/thisway/member/support/MemberFixture.java
Labels: enhancement

#20 Member 상세 조회 API 개발
  src/main/java/org/thisway/member/controller/MemberController.java
  src/main/java/org/thisway/member/dto/response/MemberResponse.java
  src/main/java/org/thisway/member/service/MemberService.java
  src/test/java/org/thisway/member/controller/MemberControllerTest.java
  src/test/java/org/thisway/member/service/MemberServiceTest.java
  src/test/java/org/thisway/member/support/MemberFixture.java
Labels: enhancement

#30 이메일 인증 코드 발송 API 구현
  .gitignore
  build.gradle
  src/main/java/org/thisway/auth/controller/AuthController.java
  src/main/java/org/thisway/auth/dto/VerificationPayload.java
  src/main/java/org/thisway/auth/dto/request/SendVerifyCodeRequest.java
  src/main/java/org/thisway/auth/service/EmailVerificationService.java
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/config/smtp/MailConfig.java
  src/main/java/org/thisway/member/repository/MemberRepository.java
  src/test/java/org/thisway/auth/controller/AuthControllerTest.java
  src/test/java/org/thisway/auth/service/EmailVerificationServiceTest.java
Labels: enhancement

#35 Vehicle 상세 조회 API
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/vehicle/controller/VehicleController.java
  src/main/java/org/thisway/vehicle/dto/response/VehicleResponse.java
  src/main/java/org/thisway/vehicle/repository/VehicleRepository.java
  src/main/java/org/thisway/vehicle/service/VehicleService.java
  src/test/java/org/thisway/vehicle/controller/VehicleControllerTest.java
  src/test/java/org/thisway/vehicle/service/VehicleServiceTest.java
Labels: enhancement

#43 Company CRUD 리팩토링
  src/main/java/org/thisway/company/dto/request/CompanyRegisterRequest.java
  src/main/java/org/thisway/company/repository/CompanyRepository.java
  src/main/java/org/thisway/company/service/CompanyService.java
Labels: enhancement, refactor

#36 로그 저장 시스템 구축
  src/main/java/org/thisway/ThiswayApplication.java
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/emulator/entity/Emulator.java
  src/main/java/org/thisway/emulator/repository/EmulatorRepository.java
  src/main/java/org/thisway/log/JdbcConfig.java
  src/main/java/org/thisway/log/controller/LogController.java
  src/main/java/org/thisway/log/dto/request/geofenceLog/GeofenceLogRequest.java
  src/main/java/org/thisway/log/dto/request/gpsLog/GpsLogEntry.java
  src/main/java/org/thisway/log/dto/request/gpsLog/GpsLogRequest.java
  src/main/java/org/thisway/log/dto/request/powerLog/PowerLogRequest.java
  src/main/java/org/thisway/log/dto/response/LogResponse.java
  src/main/java/org/thisway/log/service/LogService.java
  src/test/java/org/thisway/log/service/LogServiceTest.java
Labels: enhancement

#56 fix: EmailVerificationServiceTest에 SpyBean 어노테이션 등록
  src/test/java/org/thisway/auth/service/EmailVerificationServiceTest.java
Labels: bug

#58 Vehicle 전체 목록 조회
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/vehicle/controller/VehicleController.java
  src/main/java/org/thisway/vehicle/dto/response/VehicleResponse.java
  src/main/java/org/thisway/vehicle/dto/response/VehiclesResponse.java
  src/main/java/org/thisway/vehicle/repository/VehicleRepository.java
  src/main/java/org/thisway/vehicle/service/VehicleService.java
  src/test/java/org/thisway/vehicle/controller/VehicleControllerTest.java
  src/test/java/org/thisway/vehicle/service/VehicleServiceTest.java
Labels: enhancement

#59 Vehicle 정보 수정
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/vehicle/controller/VehicleController.java
  src/main/java/org/thisway/vehicle/dto/request/VehicleUpdateRequest.java
  src/main/java/org/thisway/vehicle/entity/Vehicle.java
  src/main/java/org/thisway/vehicle/entity/VehicleDetail.java
  src/main/java/org/thisway/vehicle/repository/VehicleRepository.java
  src/main/java/org/thisway/vehicle/service/VehicleService.java
  src/main/java/org/thisway/vehicle/validation/VehicleUpdateValidator.java
  src/test/java/org/thisway/vehicle/controller/VehicleControllerTest.java
  src/test/java/org/thisway/vehicle/service/VehicleServiceTest.java
Labels: enhancement
