Repository Kernel360/KBE5-Thisway-BE, pull requests merged in 2025-07, with the labels that each got.

#202 CI / CD 재구축 및 배포 환경 개선
  .github/workflows/cd.yml
  build.gradle
  infra/prod/monitoring/grafana/provisioning/datasources/datasource.yml
  infra/prod/monitoring/prometheus/prometheus.prod.yml
  infra/prod/rabbitmq/Dockerfile
  src/main/resources/application-prod.yml
Labels: enhancement, refactor

#215 SaveLogGps Bulk Insert로 전환
  src/main/java/org/thisway/log/repository/LogRepository.java
  src/main/java/org/thisway/log/service/GpsLogSaveService.java
  src/test/java/org/thisway/log/repository/LogRepositoryTest.java
Labels: refactor

#213 feat: #178 통계 API 배치 적용
  build.gradle
  src/main/java/org/thisway/ThiswayApplication.java
  src/main/java/org/thisway/company/repository/CompanyRepository.java
  src/main/java/org/thisway/statistics/batch/StatisticBatchConfig.java
  src/main/resources/application-prod.yml
  src/main/resources/batch-schema.sql
Labels: enhancement

#212 SSE 도입하여 API 추가
  .gitignore
  src/main/java/org/thisway/common/ErrorCode.java
  src/main/java/org/thisway/component/streaming/SseConnection.java
  src/main/java/org/thisway/component/streaming/SseEventSender.java
  src/main/java/org/thisway/config/ampq/RabbitMQConfig.java
  src/main/java/org/thisway/emulator/repository/EmulatorRepository.java
  src/main/java/org/thisway/emulator/service/EmulatorService.java
  src/main/java/org/thisway/log/consumer/SaveGpsLogConsumer.java
  src/main/java/org/thisway/log/dto/request/gpsLog/GpsLogEntry.java
  src/main/java/org/thisway/log/producer/GpsLogProducer.java
  src/main/java/org/thisway/log/repository/LogRepository.java
  src/main/java/org/thisway/log/service/GpsLogSaveService.java
  src/main/java/org/thisway/security/config/policy/triplog/TripLogAuthorizationPolicy.java
  src/main/java/org/thisway/security/utils/JwtTokenUtil.java
  src/main/java/org/thisway/triplog/consumer/StreamGpsLogConsumer.java
  src/main/java/org/thisway/triplog/controller/TripLogController.java
  src/main/java/org/thisway/triplog/dto/CoordinatesInfo.java
  src/main/java/org/thisway/triplog/dto/CurrentGpsLog.java
  src/main/java/org/thisway/triplog/dto/response/CurrentTripLogResponse.java
  src/main/java/org/thisway/triplog/dto/response/TripLogDetailResponse.java
  src/main/java/org/thisway/triplog/repository/TripLogRepository.java
  src/main/java/org/thisway/triplog/service/StreamCoordinatesService.java
  src/main/java/org/thisway/triplog/service/TripLogService.java
  src/main/java/org/thisway/triplog/service/TripLogServiceImpl.java
  src/main/java/org/thisway/vehicle/controller/VehicleController.java
  src/main/java/org/thisway/vehicle/dto/VehicleReference.java
  src/main/java/org/thisway/vehicle/repository/VehicleQueryRepository.java
  src/main/java/org/thisway/vehicle/repository/VehicleQueryRepositoryImpl.java
  src/main/java/org/thisway/vehicle/service/VehicleService.java
  src/main/java/org/thisway/vehicle/service/VehicleTrackClient.java
  src/main/java/org/thisway/vehicle/service/VehicleTrackService.java
  src/main/resources/application-dev.yml
  src/main/resources/application-prod.yml
  src/test/java/org/thisway/log/repository/LogRepositoryTest.java
  src/test/resources/application.yml
Labels: enhancement, refactor

#217 사용자 검색 기능 추가
  .gitignore
  src/main/java/org/thisway/logging/filter/LoggingFilter.java
  src/main/java/org/thisway/member/controller/CompanyChefMemberController.java
  src/main/java/org/thisway/member/controller/dto/request/CompanyChefMemberSearchRequest.java
  src/main/java/org/thisway/member/repository/MemberQueryRepository.java
  src/main/java/org/thisway/member/repository/MemberQueryRepositoryImpl.java
  src/main/java/org/thisway/member/repository/MemberRepository.java
  src/main/java/org/thisway/member/service/CompanyChefMemberService.java
  src/main/java/org/thisway/member/service/dto/CompanyChefMemberSearchCriteria.java
  src/test/java/org/thisway/member/controller/CompanyChefMemberControllerTest.java
  src/test/java/org/thisway/member/service/CompanyChefMemberServiceTest.java
Labels: enhancement

#227 feat: #220 전체 차량 조회 시 내림차순 정렬 적용
  src/main/java/org/thisway/vehicle/infrastructure/VehicleQueryRepositoryImpl.java
  src/main/java/org/thisway/vehicle/infrastructure/VehicleRepository.java
Labels: refactor
